### ISSUE TITLE
Portal wont create

### ISSUE THREAD

**Issue by Agentx49** [Multiverse/Multiverse-Portals#453] opened 2017-03-27 22:39 UTC
why wont a portal create when i use the command to create on it just says: an internal error occured when trying to perform this command i was using this modpack: https://www.technicpack.net/modpack/agentx8288-too-the-max.979149

**Comment by Jadiction** [comment] 2019-06-09 04:45
Duplicate of https://github.com/Multiverse/Multiverse-Portals/issues/484

**Closed by Jadiction** 2019-06-09 04:45 UTC
Labels: Duplicate
