### ISSUE TITLE
Error on Spigot 1.13.1 - java.lang.NoSuchMethodError: com.sk89q.worldedit.bukkit.WorldEditPlugin.getSelection

### ISSUE THREAD

**Issue by robotnikthingy** [Multiverse/Multiverse-Portals#480] opened 2018-09-02 20:31 UTC
I get this error when trying to use the /mvp create command on spigot 1.13.1 and using the latest build of Worldedit from their build server

https://hastebin.com/urejudiyuj.sql

**Comment by Jadiction** [comment] 2019-06-09 05:22
Duplicate of https://github.com/Multiverse/Multiverse-Portals/issues/475

**Closed by Jadiction** 2019-06-09 05:22 UTC
Labels: Duplicate
