### ISSUE TITLE
Support Spigot 1.12

### ISSUE THREAD

**Issue by zombachu** [Multiverse/Multiverse-Portals#457] opened 2017-05-20 06:04 UTC
1.12 removed the deprecated version of YamlConfiguration.loadConfiguration() that took InputStream as a parameter. [Problem line here](https://github.com/Multiverse/Multiverse-Portals/blob/master/src/main/java/com/onarandombox/MultiversePortals/MultiversePortals.java#L245)

**Comment by FernFerret** [comment] 2017-05-20 16:52
I'll see about fixing this today/tomorrow.

**Comment by zombachu** [comment] 2017-05-21 00:14
Ah, my bad about creating a duplicate issue. My eyes must've skipped over the other one when I checked before making this one. Thanks for the quick update, though.

**Comment by smmmadden** [comment] 2017-05-22 12:43
Hi any update on when this will be fixed?  Also, could you verify that if the plugin fails to load that it is not sending a shut down event to Spigot Server?  I have 6 plugins that fail and the server shuts down and according to Spigot, its "a plugin" that is the cause.  I've reported on the other 5 plugin pages and now this one. :-)  Thanks!

**Comment by FernFerret** [comment] 2017-05-22 15:39
I did not get a chance to look at this during the weekend, sorry. To be
clear, I don't think it's a big fix at all (should be easy) but I just ran
out of time.

**Comment by FernFerret** [comment] 2017-05-23 17:03
Yep, I hear ya. I'd been slacking (for the past few years haha) on keeping
the sub components up-to-date. Y'all have *not* been forgotten and I will
get to it sometime this week, not sure when though...

**Comment by chrismin13** [comment] 2017-05-31 13:46
Done. Change line 245 to:

  Configuration portalsDefaults = YamlConfiguration.loadConfiguration(new InputStreamReader(this.getClass().getResourceAsStream("/defaults/config.yml"), Charsets.UTF_8));

Also, add Spigot 1.12-pre6 to the pom.xml, but make sure it's at the top of the dependencies, otherwise it won't work.

Below is a compiled and tested version. Had trouble creating a pull request, so this will do for now. Enjoy!

[Multiverse-Portals-2.5.0-SNAPSHOT.jar.zip](https://github.com/Multiverse/Multiverse-Portals/files/1041688/Multiverse-Portals-2.5.0-SNAPSHOT.jar.zip)

**Comment by FernFerret** [comment] 2017-05-31 22:36
Saw the official is releasing this friday, so I guarantee this will be
added to the baseline by then (hopefully tonight).

On Wed, May 31, 2017 at 7:46 AM, Christos Miniotis <notifications@github.com

**Comment by smmmadden** [comment] 2017-06-01 02:41
@chrismin13 - looks like the build is missing from the plugin.yml
authors: ['Rigby', 'fernferret']
version: 2.5.0-SNAPSHOT-b**UNKNOWN**

**Closed** 2017-06-01 03:21 UTC
Labels: Bug

**Comment by FernFerret** [comment] 2017-06-01 06:21
Thanks @dumptruckman. I figure If I just keep saying I'm going to do
something someone else on the team will actually do it :)

**Comment by TheRealB** [comment] 2017-06-01 19:39
Maybe its possible to start an build process on the jenkins?

**Comment by dumptruckman** [comment] 2017-06-01 23:51
Weird. Not sure why it didn't build automatically. I just triggered a build now.
