### ISSUE TITLE
MVP issue

### ISSUE THREAD

**Issue by Rookie-G** [Multiverse/Multiverse-Portals#419] opened 2016-03-12 20:19 UTC
So FlameSurvival is currently having problems with their MVP plugin, we are trying to use it but no matter what command we execute we get error messages. 
We assume that the issue is the recent Minecraft update for 1.9, we use this version on the current server we have problems with. We are just wondering if it was a problem with the version of MC or just a bug in the system. Any replies with useful information will be appreciated.
Thanks,
-Rookie

**Comment by FernFerret** [comment] 2016-03-12 23:06
Multiverse-Portals is indeed updated for 1.9.

- [ ] Make sure you're using the latest versions from http://ci.onarandombox.com
- [ ] Please see [Submitting a bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and follow those steps to produce a well written ticket.

**Comment by Rookie-G** [comment] 2016-03-13 08:50
._. The link helped, thanks... .

**Comment by FernFerret** [comment] 2016-03-13 16:15
Um... alright? I'm going to close this ticket because I'm unsure if you're serious or not.

The links I sent you do apply to MVP as well. This is not a well written bug report. You're saying you see error messages but don't state them. If there is an issue how easy is it to reproduce? All of those questions can be answered with the information.

**Closed by FernFerret** 2016-03-13 16:15 UTC
Labels: Not Enough Information
