### ISSUE TITLE
Issues with Vehicles in Multiverse-Portals 3.0.0-SNAPSHOT-b785

### ISSUE THREAD

**Issue by Jalrashu** [Multiverse/Multiverse-Portals#494] opened 2019-01-31 18:20 UTC
**Expected Behavior:** When driving a mine cart or boat (unsure of support) through a portal, it should transport the cart to the portals destination.

**Actual Behavior:** Driving a mine cart through a portal that goes to another world achieves intended success, transporting mine cart and user. If the portals destination is within the same world, nothing occurs, Boats do not appear to functional at all. This was tested using the following destination types: Anchors, Portals, Worlds.

Multiverse-Portals version is 3.0.0-SNAPRSHOT-b785
Multiverse-Core version is  3.0.0-SNAAPSHOT-B758

**Comment by dumptruckman** [comment] 2019-01-31 21:09
Duplicate of #267

**Closed by dumptruckman** 2019-01-31 21:09 UTC
