### ISSUE TITLE
Feature Request: Timed or Delayed portals

### ISSUE THREAD

**Issue by indiealexh** [Multiverse/Multiverse-Portals#187] opened 2012-08-13 09:46 UTC
HI, I have a ship on my server as a portal Id like to have a delay from the person entering the portal to teleport.
I would code itmyself But I simply dont have time at the moment, If you reject my preposal, somtime in the future I will do this anyways.

**Comment by FernFerret** [comment] 2016-03-08 03:22
Closing as duplicate of #235 (yep, I'm doing these in reverse order, whoops!)

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

**Closed by FernFerret** 2016-03-08 03:22 UTC
Labels: Duplicate
