### ISSUE TITLE
Unable to teleport with a Minecart

### ISSUE THREAD

**Issue by Vellric** [Multiverse/Multiverse-Portals#420] opened 2016-03-16 17:39 UTC
I'm trying to use a MV Portal with a Minecart and it don't work. I don't know if I'm doing something wrong or what. When I pass with a vehicule in the portal, nothing happen. On foot, it work. It does the same on a fresh server with only Multiverse and Multiverse-Portals install as plugin. Spigot and Java are up to date.

My config : http://pastebin.com/bL6iRThv
A video where I reproduce the problem : https://www.youtube.com/watch?v=W_IRXB5gNhg

**Comment by FernFerret** [comment] 2016-03-19 00:43
I need to update my test environment, as this should work, but I won't have the time for a week or two. This is also highly related to #267.

**Comment by Vellric** [comment] 2016-03-30 00:41
Hey @FernFerret ! I was wondering how it goes for that? I'm waiting with patience for news from you!

**Comment by Jadiction** [comment] 2019-06-09 05:05
Duplicate of https://github.com/Multiverse/Multiverse-Portals/issues/267

**Closed by Jadiction** 2019-06-09 05:05 UTC
Labels: Duplicate
