### ISSUE TITLE
Recommended feature to add!

### ISSUE THREAD

**Issue by ci29995** [Multiverse/Multiverse-Portals#196] opened 2012-09-16 21:12 UTC
Please add these features from the world portal plugin.
I hate making a huge structure just to make a portal. Why can't it just be a simple button?
Please please PLEASE add this feature!!!

"Teleport to other locations and world with signs, pressure plates, buttons and more
Easily create portals using a single command "

plugin: http://dev.bukkit.org/server-mods/world-portal/

Add this in the next update, i will to donate to you guys for all your help!

**Comment by FernFerret** [comment] 2016-03-08 03:05
Command blocks can be used to perform commands via button presses and whatnot.

I think this issue is a duplicate of your other one, but again, please reopen with more information if you still think we don't meet the requirement.

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great!

**Closed by FernFerret** 2016-03-08 03:05 UTC
