### ISSUE TITLE
error starting - deleted folder -  Multiverse-Portals v2.5.2-SNAPSHOT-b765

### ISSUE THREAD

**Issue by DaDMaR** [Multiverse/Multiverse-Portals#478] opened 2018-08-18 14:34 UTC
[00:17:51 INFO]: This server is running CraftBukkit version git-Spigot-fe3ab0d-bfb9131 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

[00:18:04 INFO]: [Multiverse-Portals] Enabling Multiverse-Portals v2.5.2-SNAPSHOT-b765
[00:18:04 INFO]: [Multiverse-Portals] - Version 2.5.2-SNAPSHOT-b765 Enabled - By Rigby and fernferret
[00:18:04 INFO]: [MVPLogging] 0 - Portals(s) loaded
[00:18:04 ERROR]: Error occurred while enabling Multiverse-Portals v2.5.2-SNAPSHOT-b765 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/bukkit/WorldEditAPI
	at com.onarandombox.MultiversePortals.WorldEditConnection.connect(WorldEditConnection.java:47) ~[?:?]
	at com.onarandombox.MultiversePortals.MultiversePortals.checkForWorldEdit(MultiversePortals.java:174) ~[?:?]
	at com.onarandombox.MultiversePortals.MultiversePortals.onEnable(MultiversePortals.java:141) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-bfb9131]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.jar:git-Spigot-fe3ab0d-bfb9131]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.jar:git-Spigot-fe3ab0d-bfb9131]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:426) [spigot-1.13.jar:git-Spigot-fe3ab0d-bfb9131]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:340) [spigot-1.13.jar:git-Spigot-fe3ab0d-bfb9131]
	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562) [spigot-1.13.jar:git-Spigot-fe3ab0d-bfb9131]
	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524) [spigot-1.13.jar:git-Spigot-fe3ab0d-bfb9131]
	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423) [spigot-1.13.jar:git-Spigot-fe3ab0d-bfb9131]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [spigot-1.13.jar:git-Spigot-fe3ab0d-bfb9131]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot-1.13.jar:git-Spigot-fe3ab0d-bfb9131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.bukkit.WorldEditAPI
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-bfb9131]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-bfb9131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	... 14 more

**Comment by Jadiction** [comment] 2019-06-09 05:21
Duplicate of https://github.com/Multiverse/Multiverse-Portals/issues/475

**Closed by Jadiction** 2019-06-09 05:21 UTC
Labels: Duplicate
