### ISSUE TITLE
Using portals cause the worlds.yml to revert settings.

### ISSUE THREAD

**Issue by Ezence** [Multiverse/Multiverse-Portals#312] opened 2014-04-13 19:34 UTC
When using a portal to exit a world the worlds difficulty setting is reverted back to the server default and saved back to worlds.yml.

This can be replicated by creating 2 worlds and setting the difficulty of one to NORMAL and the other to PEACEFUL as well as the server default. When you exit World2 (normal) it will save the difficulty back to worlds.yml as PEACEFUL.

**Comment by FernFerret** [comment] 2016-03-06 21:41
@Favorlock thanks for the report, marking unable to reproduce right now.

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).

**Closed** 2016-03-06 21:41 UTC
Labels: Can't Reproduce
