### ISSUE TITLE
Multiverse-Portals Error

### ISSUE THREAD

**Issue by Elementkingaming** [Multiverse/Multiverse-Portals#458] opened 2017-06-21 01:36 UTC
Hey, im using Multiverse-Portals and unlike most people im able to create a portal, but it keeps having a error saying "No Safe Locations Found" and i looked at another guys issue (had the same problem as me) and you said to use the exact destination? and i have no idea what that means

**Comment by wapjoe** [comment] 2017-07-01 15:25
Perhaps no block is located below the spawnpoint (0, 64, 0)?

**Comment by Elementkingaming** [comment] 2017-07-02 21:02
No, I have a whole circle around the water, and blocks at the top to stop
it over flowing, and I selected all the block around it

On 2/07/2017 3:25 am, "wapjoe" <notifications@github.com> wrote:

Perhaps no block is located below the spawnpoint (0, 64, 0)?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Multiverse/Multiverse-Portals/issues/458#issuecomment-312438197>,
or mute the thread

**Comment by wapjoe** [comment] 2017-07-03 20:48
I can only reproduce your problem with a large hole (9x9 blocks) in the ground. Can you make a screenshot?
![2017-07-03 22_45_24-minecraft 1 12](https://user-images.githubusercontent.com/24509200/27807507-97ebdc74-6041-11e7-880e-0a148a41017a.png)

**Comment by Jadiction** [comment] 2019-06-09 04:47
Closing ticket because it's years old. Update to the latest versions of Multiverse (Core, Portals and any others you may use). Please open a new ticket if this issue persists.

**Closed by Jadiction** 2019-06-09 04:47 UTC

**Comment by FunixT** [comment] 2021-06-27 12:13
I simply used /mv tp "ur name" "ur world name"
then i typed /mvconfirm
and built a pad under the spawn
