### ISSUE TITLE
Mounted Units Teleportation

### ISSUE THREAD

**Issue by Noumpas13** [Multiverse/Multiverse-Portals#339] opened 2014-08-07 14:27 UTC
When you walk in a portal mounted on a horse, you teleport at the other side without the horse (or big/or whatever)
I would appreciate if you could make an option for each portal to accept mobs or mounted units such as horses.

many of my players want to buy a horse from spawn and use a portal to take it to another world or another location but they cannot, and i have to spawn everything in a different area.

**Comment by FernFerret** [comment] 2016-03-06 21:17
Closing as duplicate of #267

**Closed by FernFerret** 2016-03-06 21:17 UTC
