### ISSUE TITLE
total clean server no cart tp

### ISSUE THREAD

**Issue by ardentcrest** [Multiverse/Multiverse-Portals#452] opened 2017-03-22 15:38 UTC
on a clean server.
latest spigot 1.11.2
plugin : (all latest) Core, portal, worldedit (nothing else)

no carts(any of them) full or empty will TP from in same world or across worlds
all they do is flash on and off in the portals

Is there a fix. how do I get carts though portals.

**Comment by ardentcrest** [comment] 2017-03-23 18:04
Wait. What. Was that a reply. NO. Just wishful thinking.  :D

**Comment by ardentcrest** [comment] 2017-03-28 16:20
still nothing.

**Comment by Jadiction** [comment] 2019-06-09 05:04
Duplicate of https://github.com/Multiverse/Multiverse-Portals/issues/267

**Closed by Jadiction** 2019-06-09 05:04 UTC
Labels: Duplicate
