### ISSUE TITLE
Mobs-Hostile or Tame.

### ISSUE THREAD

**Issue by LordDWT** [Multiverse/Multiverse-Portals#469] opened 2018-01-07 21:06 UTC
Can you add an option in config to allow Mobs to travel through portals?

**Comment by LordDWT** [comment] 2018-03-03 11:34
Any word on this?

**Comment by Jadiction** [comment] 2019-06-09 05:04
Duplicate of https://github.com/Multiverse/Multiverse-Portals/issues/267

**Closed by Jadiction** 2019-06-09 05:04 UTC
Labels: Duplicate
