### ISSUE TITLE
1.14 upgrade

### ISSUE THREAD

**Issue by SlimeDog** [Multiverse/Multiverse-Portals#503] opened 2019-04-30 14:11 UTC
Spigot 1.14 (2235 and previous)
Multiverse-Core 3.0.0-SNAPSHOT-b761
Multiverse-Portals 3.0.0-SNAPSHOT-b790

On server start-up
```
[06:43:02] [Server thread/ERROR]: Error occurred while enabling Multiverse-Portals v3.0.0-SNAPSHOT-b790 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/TravelAgent
        at com.onarandombox.MultiversePortals.MultiversePortals.registerEvents(MultiversePortals.java:152) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.onEnable(MultiversePortals.java:144) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.jar-2019-04-30-0641:git-Spigot-1eece4f-dadc539]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.jar-2019-04-30-0641:git-Spigot-1eece4f-dadc539]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot-1.14.jar-2019-04-30-0641:git-Spigot-1eece4f-dadc539]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot-1.14.jar-2019-04-30-0641:git-Spigot-1eece4f-dadc539]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot-1.14.jar-2019-04-30-0641:git-Spigot-1eece4f-dadc539]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [spigot-1.14.jar-2019-04-30-0641:git-Spigot-1eece4f-dadc539]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.jar-2019-04-30-0641:git-Spigot-1eece4f-dadc539]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:758) [spigot-1.14.jar-2019-04-30-0641:git-Spigot-1eece4f-dadc539]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.TravelAgent
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.14.jar-2019-04-30-0641:git-Spigot-1eece4f-dadc539]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.jar-2019-04-30-0641:git-Spigot-1eece4f-dadc539]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 11 more
```

**Comment by cheesepufftyler** [comment] 2019-05-04 23:19
I have the same issue. Portals wont work at all.

**Comment by MonstahGames** [comment] 2019-05-05 00:19
Same here.

**Comment by MonstahGames** [comment] 2019-05-05 00:20
I'm guessing this would be a similar fix like the PR in -Core

**Comment by cheesepufftyler** [comment] 2019-05-05 03:12
how so? @MonstahGames

**Comment by MonstahGames** [comment] 2019-05-05 09:16
@cheesepufftyler The error in console says that it can't find TravelAgent, this is  because it was removed in 1.14. It was a similar thing in -Core

**Comment by MonstahGames** [comment] 2019-05-05 12:08
I made a PR for this at #504

**Comment by SlimeDog** [comment] 2019-05-05 16:05
Have we lost the dumptruckman ?

**Comment by DaDMaR** [comment] 2019-05-09 12:54
yep looks the same reason I had to remove it
Spigot-1eece4f-fe1199c (MC: 1.14) API version 1.14-R0.1-SNAPSHOT
Multiverse-Core 3.0.0-SNAPSHOT-b761
Multiverse-Portals 3.0.0-SNAPSHOT-b790

On server start-up

[22:39:25] [Server thread/INFO]: [Multiverse-Portals] Enabling Multiverse-Portals v3.0.0-SNAPSHOT-b790
[22:39:25] [Server thread/INFO]: [Multiverse-Portals] - Version 3.0.0-SNAPSHOT-b790 Enabled - By Rigby and fernferret
[22:39:25] [Server thread/INFO]: [MVPLogging] 0 - Portals(s) loaded
[22:39:25] [Server thread/ERROR]: Error occurred while enabling Multiverse-Portals v3.0.0-SNAPSHOT-b790 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/TravelAgent
	at com.onarandombox.MultiversePortals.MultiversePortals.registerEvents(MultiversePortals.java:152) ~[?:?]
	at com.onarandombox.MultiversePortals.MultiversePortals.onEnable(MultiversePortals.java:144) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.jar:git-Spigot-1eece4f-fe1199c]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.jar:git-Spigot-1eece4f-fe1199c]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot-1.14.jar:git-Spigot-1eece4f-fe1199c]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot-1.14.jar:git-Spigot-1eece4f-fe1199c]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot-1.14.jar:git-Spigot-1eece4f-fe1199c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:441) [spigot-1.14.jar:git-Spigot-1eece4f-fe1199c]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.jar:git-Spigot-1eece4f-fe1199c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:762) [spigot-1.14.jar:git-Spigot-1eece4f-fe1199c]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.ClassNotFoundException: org.bukkit.TravelAgent
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.14.jar:git-Spigot-1eece4f-fe1199c]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.jar:git-Spigot-1eece4f-fe1199c]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
	... 11 more

**Comment by MonstahGames** [comment] 2019-05-09 13:00
Yeah, TravelAgent was removed in 1.14. It's fixed in my pr

**Comment by Jadiction** [comment] 2019-06-09 05:36
This is fixed in the latest version of the Multiverse plugins.

**Closed by Jadiction** 2019-06-09 05:36 UTC
