### ISSUE TITLE
Creating a portal next to void causes main thread hangup

### ISSUE THREAD

**Issue by XHawk87** [Multiverse/Multiverse-Portals#282] opened 2013-08-27 12:39 UTC
Creating a multiverse portal at bedrock level, right next to the void, and going through it causes the server's main thread to get blocked indefinitely, requiring a restart. The problem is tied to the player's .dat file, so that if that player signs in again the server freezes again (probably due to the player's continued proximity inside the portal?). Renaming or deleting the player's .dat file fixes the issue.

Steps to reproduce:

1) Hollow out an area down to the void, through the bedrock
2) Select a region at the lowest bedrock level, the very bottom of the map, 1 block high
3) Create a /mvp portal using this region and link it to a different world
4) Attempt to travel through it

**Comment by FernFerret** [comment] 2016-03-06 22:16
Unable to reproduce, is this what you're talking about? 
![image](https://cloud.githubusercontent.com/assets/72811/13557472/507873f4-e3ae-11e5-91a7-20cccc2a7b51.png)

![image](https://cloud.githubusercontent.com/assets/72811/13557477/5baccc70-e3ae-11e5-801c-25d8ca5c5e3a.png)


I built the portal bounds in the blue wool, lowest is at the bottom. If this was an issue, sounds like it was a CB issue.

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).

**Closed by FernFerret** 2016-03-06 22:16 UTC

**Comment by XHawk87** [comment] 2016-03-06 22:29
I have no idea if this is still an issue. To be honest, it took me a while to remember posting it. I believe it had something to do with a vertical facing portal where the entire portal is at y=0 and the entire portal region is empty (air), but I can't be sure. The server it was running on no longer exists, and I am pretty sure I ended up using Skript to make the portal instead.

Good luck with the cleaning!
