### ISSUE TITLE
Mounted Animals Teleport

### ISSUE THREAD

**Issue by zerafox** [Multiverse/Multiverse-Portals#421] opened 2016-03-19 00:36 UTC
Would it be possible to allow the Teleportation of a Mounted/Led Entities through portals?
Such as Horses and ridden Pigs? Or Led sheep and cows?
Or any entity for that matter.

I ask as there are quite a few mount plugins out there, but with the inability to take them through portals our poor friends are restricted to certain worlds, whether or not it's the mount plugin saying so or not.

**Comment by FernFerret** [comment] 2016-03-19 00:42
Closing as duplicate of #267. We're aware :smile:

**Closed by FernFerret** 2016-03-19 00:42 UTC
