### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by JackHubbleday** [Multiverse/Multiverse-Portals#445] opened 2016-12-28 16:35 UTC
Please see attached:

**Comment by JackHubbleday** [comment] 2016-12-28 16:35
https://www.mediafire.com/?zf2im2tsbnfbu9v

**Comment by Jadiction** [comment] 2019-06-09 04:41
Duplicate of https://github.com/Multiverse/Multiverse-Portals/issues/484

**Closed by Jadiction** 2019-06-09 04:41 UTC
Labels: Duplicate
