### ISSUE TITLE
Tamed wolves and cats not following through portals - Feature request

### ISSUE THREAD

**Issue by RabidFX** [Multiverse/Multiverse-Portals#184] opened 2012-08-06 13:47 UTC
Pretty much everything is in the title. 

On portal activation, could it be possible to check if a tamed cat or wolf is in a certain radius of a player going through a portal, and teleporting it there with him ?

**Comment by FernFerret** [comment] 2016-03-08 03:30
Closing as duplicate of #267

**Closed by FernFerret** 2016-03-08 03:30 UTC
Labels: Duplicate
