### ISSUE TITLE
Worldedit 7.0 isn't supported

### ISSUE THREAD

**Issue by Sprungente** [Multiverse/Multiverse-Portals#479] opened 2018-09-01 20:01 UTC
So the plugin isn't work well on 1.13.

**Comment by lifehome** [comment] 2018-12-27 16:00
I think #488 have fixed the issue. Have you tried it out?

**Comment by Jadiction** [comment] 2019-06-09 05:22
Duplicate of https://github.com/Multiverse/Multiverse-Portals/issues/475

**Closed by Jadiction** 2019-06-09 05:22 UTC
Labels: Duplicate
