### ISSUE TITLE
Cant create Portals?

### ISSUE THREAD

**Issue by Sproose-Moose** [Multiverse/Multiverse-Portals#449] opened 2017-02-07 00:29 UTC
I am trying to connect worlds in a server with my friends with portals so I downloaded this plugin but when I type the command it says "An internal error occurred while trying to perform this command" I have read other conversations and have put my server script in this comment so someone can help me find the problem. I have also highlighted where I typed the command.

C:\Users\jill_000\Downloads\BuildTools>java -Xms512M -Xmx1G -XX:+UseConcMarkSweepGC -jar spigot-1.11.2.jar
Loading libraries, please wait...
[19:23:57 INFO]: Starting minecraft server version 1.11.2
[19:23:57 INFO]: Loading properties
[19:23:57 INFO]: Default game type: CREATIVE
[19:23:57 INFO]: This server is running CraftBukkit version git-Spigot-4741400-a1d3777 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
[19:23:57 WARN]: Failed to load white-list:
java.lang.NullPointerException
        at net.minecraft.server.v1_11_R1.JsonList.load(JsonList.java:195) ~[spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at net.minecraft.server.v1_11_R1.DedicatedPlayerList.C(SourceFile:123) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at net.minecraft.server.v1_11_R1.DedicatedPlayerList.<init>(SourceFile:30) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:182) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
[19:23:58 INFO]: Debug logging is disabled
[19:23:58 INFO]: Using 4 threads for Netty based IO
[19:23:58 INFO]: Server Ping Player Sample Count: 12
[19:23:58 INFO]: Generating keypair
[19:23:58 INFO]: Starting Minecraft server on 192.168.2.105:25565
[19:23:58 INFO]: Using default channel type
[19:23:58 ERROR]: Ambiguous plugin name `Multiverse-Core' for files `plugins\Multiverse-Core-2.5.jar' and `plugins\Multiverse-Core-2.4.jar' in `plugins'
[19:23:58 INFO]: Set PluginClassLoader as parallel capable
[19:23:59 INFO]: [WorldEdit] Loading WorldEdit v6.1.5;4651611
[19:23:59 INFO]: [Lockette] Loading Lockette v1.8.23
[19:23:59 INFO]: [Vault] Loading Vault v1.5.6-b49
[19:23:59 INFO]: [SaneEconomy] Loading SaneEconomy v0.10.4
[19:23:59 INFO]: [Multiverse-Core] Loading Multiverse-Core v2.5-b699
[19:23:59 INFO]: [WorldGuard] Loading WorldGuard v6.1.3-SNAPSHOT;c904242
[19:23:59 INFO]: [CraftBook] Loading CraftBook v3.9-SNAPSHOT
[19:23:59 INFO]: [ShopChest] Loading ShopChest v1.11.1
[19:23:59 INFO]: [ShopChest] Using locale "en_US"
[19:23:59 INFO]: [Multiverse-Portals] Loading Multiverse-Portals v2.4-b548
[19:23:59 INFO]: [Vault] Enabling Vault v1.5.6-b49
[19:23:59 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[19:23:59 INFO]: [Vault] Enabled Version 1.5.6-b49
[19:23:59 INFO]: [SaneEconomy] Enabling SaneEconomy v0.10.4
[19:23:59 INFO]: [SaneEconomy] Initializing currency...
[19:23:59 INFO]: [SaneEconomy] Initialized currency: dollars
[19:23:59 INFO]: [SaneEconomy] Initializing economy storage backend...
[19:23:59 INFO]: [SaneEconomy] Initialized flatfile backend with file C:\Users\jill_000\Downloads\BuildTools\plugins\SaneEconomy\economy.db
[19:23:59 INFO]: [SaneEconomy] Performing initial data load...
[19:23:59 INFO]: [SaneEconomy] Data loaded!
[19:23:59 INFO]: [SaneEconomy] Initializing commands...
[19:23:59 INFO]: [SaneEconomy] Initialized commands.
[19:23:59 INFO]: [SaneEconomy] Initializing listeners...
[19:23:59 INFO]: [SaneEconomy] Initialized listeners.
[19:23:59 INFO]: [SaneEconomy] Hooked into Vault.
[19:23:59 INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[19:23:59 INFO]: Preparing level "world"
[19:23:59 INFO]: -------- World Settings For [world] --------
[19:23:59 INFO]: Item Despawn Rate: 6000
[19:23:59 INFO]: Item Merge Radius: 2.5
[19:23:59 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[19:23:59 INFO]: Arrow Despawn Rate: 1200
[19:23:59 INFO]: Experience Merge Radius: 3.0
[19:23:59 INFO]: Zombie Aggressive Towards Villager: true
[19:23:59 INFO]: View Distance: 10
[19:23:59 INFO]: Nerfing mobs spawned from spawners: false
[19:23:59 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617Monument: 10387313 Slime: 987234911
[19:23:59 INFO]: Mob Spawn Range: 4
[19:23:59 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[19:23:59 INFO]: Structure Info Saving: true
[19:23:59 INFO]: Max TNT Explosions: 100
[19:23:59 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[19:23:59 INFO]: Cactus Growth Modifier: 100%
[19:23:59 INFO]: Cane Growth Modifier: 100%
[19:23:59 INFO]: Melon Growth Modifier: 100%
[19:23:59 INFO]: Mushroom Growth Modifier: 100%
[19:23:59 INFO]: Pumpkin Growth Modifier: 100%
[19:23:59 INFO]: Sapling Growth Modifier: 100%
[19:23:59 INFO]: Wheat Growth Modifier: 100%
[19:23:59 INFO]: NetherWart Growth Modifier: 100%
[19:23:59 INFO]: Vine Growth Modifier: 100%
[19:23:59 INFO]: Cocoa Growth Modifier: 100%
[19:23:59 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[19:23:59 INFO]: Random Lighting Updates: false
[19:23:59 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[19:23:59 INFO]: -------- World Settings For [world_nether] --------
[19:23:59 INFO]: Item Despawn Rate: 6000
[19:23:59 INFO]: Item Merge Radius: 2.5
[19:23:59 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[19:23:59 INFO]: Arrow Despawn Rate: 1200
[19:23:59 INFO]: Experience Merge Radius: 3.0
[19:23:59 INFO]: Zombie Aggressive Towards Villager: true
[19:23:59 INFO]: View Distance: 10
[19:23:59 INFO]: Nerfing mobs spawned from spawners: false
[19:23:59 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617Monument: 10387313 Slime: 987234911
[19:23:59 INFO]: Mob Spawn Range: 4
[19:23:59 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[19:23:59 INFO]: Structure Info Saving: true
[19:23:59 INFO]: Max TNT Explosions: 100
[19:23:59 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[19:23:59 INFO]: Cactus Growth Modifier: 100%
[19:23:59 INFO]: Cane Growth Modifier: 100%
[19:24:00 INFO]: Melon Growth Modifier: 100%
[19:24:00 INFO]: Mushroom Growth Modifier: 100%
[19:24:00 INFO]: Pumpkin Growth Modifier: 100%
[19:24:00 INFO]: Sapling Growth Modifier: 100%
[19:24:00 INFO]: Wheat Growth Modifier: 100%
[19:24:00 INFO]: NetherWart Growth Modifier: 100%
[19:24:00 INFO]: Vine Growth Modifier: 100%
[19:24:00 INFO]: Cocoa Growth Modifier: 100%
[19:24:00 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[19:24:00 INFO]: Random Lighting Updates: false
[19:24:00 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[19:24:00 INFO]: -------- World Settings For [world_the_end] --------
[19:24:00 INFO]: Item Despawn Rate: 6000
[19:24:00 INFO]: Item Merge Radius: 2.5
[19:24:00 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[19:24:00 INFO]: Arrow Despawn Rate: 1200
[19:24:00 INFO]: Experience Merge Radius: 3.0
[19:24:00 INFO]: Zombie Aggressive Towards Villager: true
[19:24:00 INFO]: View Distance: 10
[19:24:00 INFO]: Nerfing mobs spawned from spawners: false
[19:24:00 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617Monument: 10387313 Slime: 987234911
[19:24:00 INFO]: Mob Spawn Range: 4
[19:24:00 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[19:24:00 INFO]: Structure Info Saving: true
[19:24:00 INFO]: Max TNT Explosions: 100
[19:24:00 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[19:24:00 INFO]: Cactus Growth Modifier: 100%
[19:24:00 INFO]: Cane Growth Modifier: 100%
[19:24:00 INFO]: Melon Growth Modifier: 100%
[19:24:00 INFO]: Mushroom Growth Modifier: 100%
[19:24:00 INFO]: Pumpkin Growth Modifier: 100%
[19:24:00 INFO]: Sapling Growth Modifier: 100%
[19:24:00 INFO]: Wheat Growth Modifier: 100%
[19:24:00 INFO]: NetherWart Growth Modifier: 100%
[19:24:00 INFO]: Vine Growth Modifier: 100%
[19:24:00 INFO]: Cocoa Growth Modifier: 100%
[19:24:00 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[19:24:00 INFO]: Random Lighting Updates: false
[19:24:00 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[19:24:00 INFO]: Preparing start region for level 0 (Seed: -2904687141688286037)
[19:24:01 INFO]: Preparing spawn area: 0%
[19:24:02 INFO]: Preparing spawn area: 12%
[19:24:03 INFO]: Preparing spawn area: 31%
[19:24:04 INFO]: Preparing spawn area: 48%
[19:24:05 INFO]: Preparing spawn area: 65%
[19:24:06 INFO]: Preparing spawn area: 78%
[19:24:07 INFO]: Preparing spawn area: 99%
[19:24:07 INFO]: Preparing start region for level 1 (Seed: -2904687141688286037)
[19:24:08 INFO]: Preparing spawn area: 16%
[19:24:09 INFO]: Preparing spawn area: 35%
[19:24:10 INFO]: Preparing spawn area: 52%
[19:24:11 INFO]: Preparing spawn area: 73%
[19:24:12 INFO]: Preparing spawn area: 92%
[19:24:12 INFO]: Preparing start region for level 2 (Seed: -2904687141688286037)
[19:24:13 INFO]: [WorldEdit] Enabling WorldEdit v6.1.5;4651611
[19:24:14 INFO]: WEPIF: Using the Bukkit Permissions API.
[19:24:14 INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_11_R1 as the Bukkit adapter
[19:24:14 INFO]: [Lockette] Enabling Lockette v1.8.23
[19:24:14 INFO]: [Lockette] Version 1.8.23 is being enabled!  Yay!  (Core version 1.3.5)
[19:24:14 INFO]: minor >
[19:24:14 INFO]: [Lockette] Detected Bukkit version [v1_11_R1] ok.
[19:24:14 INFO]: [Lockette] Custom lockable block list: [116, 84, 57, 145, 154]
[19:24:14 INFO]: [Lockette] Ignoring linked plugins: [mcMMO]
[19:24:14 INFO]: [Lockette] Loading strings file for English by Acru
[19:24:14 INFO]: [Lockette] Using ops file for admin permissions.
[19:24:14 INFO]: [Lockette] Ready to protect your containers.
[19:24:14 INFO]: [Multiverse-Core] Enabling Multiverse-Core v2.5-b699
[19:24:14 INFO]: -------- World Settings For [Survivalness] --------
[19:24:14 INFO]: Item Despawn Rate: 6000
[19:24:14 INFO]: Item Merge Radius: 2.5
[19:24:14 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[19:24:14 INFO]: Arrow Despawn Rate: 1200
[19:24:14 INFO]: Experience Merge Radius: 3.0
[19:24:14 INFO]: Zombie Aggressive Towards Villager: true
[19:24:14 INFO]: View Distance: 10
[19:24:14 INFO]: Nerfing mobs spawned from spawners: false
[19:24:14 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617Monument: 10387313 Slime: 987234911
[19:24:14 INFO]: Mob Spawn Range: 4
[19:24:14 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[19:24:14 INFO]: Structure Info Saving: true
[19:24:14 INFO]: Max TNT Explosions: 100
[19:24:14 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[19:24:14 INFO]: Cactus Growth Modifier: 100%
[19:24:14 INFO]: Cane Growth Modifier: 100%
[19:24:14 INFO]: Melon Growth Modifier: 100%
[19:24:14 INFO]: Mushroom Growth Modifier: 100%
[19:24:14 INFO]: Pumpkin Growth Modifier: 100%
[19:24:14 INFO]: Sapling Growth Modifier: 100%
[19:24:14 INFO]: Wheat Growth Modifier: 100%
[19:24:14 INFO]: NetherWart Growth Modifier: 100%
[19:24:14 INFO]: Vine Growth Modifier: 100%
[19:24:14 INFO]: Cocoa Growth Modifier: 100%
[19:24:14 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[19:24:14 INFO]: Random Lighting Updates: false
[19:24:14 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[19:24:14 INFO]: Preparing start region for level 3 (Seed: 5564268083157372005)
[19:24:23 INFO]: [Multiverse-Core] 4 - World(s) loaded.
[19:24:23 INFO]: [Multiverse-Core] Version 2.5-b699 (API v19) Enabled - By Rigby, fernferret, lithium3141 and main--
[19:24:23 INFO]: [WorldGuard] Enabling WorldGuard v6.1.3-SNAPSHOT;c904242
[19:24:24 INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[19:24:24 INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[19:24:24 INFO]: [WorldGuard] (world) Lava fire is blocked.
[19:24:24 INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[19:24:24 INFO]: [WorldGuard] Loaded configuration for world 'world'
[19:24:24 INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
[19:24:24 INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
[19:24:24 INFO]: [WorldGuard] (world_nether) Lava fire is blocked.
[19:24:24 INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
[19:24:24 INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
[19:24:24 INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
[19:24:24 INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[19:24:24 INFO]: [WorldGuard] (world_the_end) Lava fire is blocked.
[19:24:24 INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[19:24:24 INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[19:24:24 INFO]: [WorldGuard] (Survivalness) TNT ignition is PERMITTED.
[19:24:24 INFO]: [WorldGuard] (Survivalness) Lighters are PERMITTED.
[19:24:24 INFO]: [WorldGuard] (Survivalness) Lava fire is blocked.
[19:24:24 INFO]: [WorldGuard] (Survivalness) Fire spread is UNRESTRICTED.
[19:24:24 INFO]: [WorldGuard] Loaded configuration for world 'Survivalness'
[19:24:24 INFO]: [WorldGuard] Loading region data...
[19:24:24 INFO]: [CraftBook] Enabling CraftBook v3.9-SNAPSHOT
[19:24:24 INFO]: [CraftBook] Loading persistent data from YAML!
[19:24:24 INFO]: [CraftBook] The Auto-Updater is disabled for your version!
[19:24:24 INFO]: [ShopChest] Enabling ShopChest v1.11.1
[19:24:24 INFO]: [ShopChest] Using SQLite
[19:24:24 INFO]: [ShopChest] Initialized 0 Shops
[19:24:24 INFO]: [Multiverse-Portals] Enabling Multiverse-Portals v2.4-b548
[19:24:24 INFO]: [Multiverse-Portals] - Version 2.4-b548 Enabled - By Rigby and fernferret
[19:24:24 INFO]: [Multiverse-Portals]  0 - Portals(s) loaded
[19:24:24 INFO]: Server permissions file permissions.yml is empty, ignoring it
[19:24:24 INFO]: Done (25.258s)! For help, type "help" or "?"
[19:24:24 WARN]: [Multiverse-Core] Plugin Multiverse-Core v2.5-b699 generated an exception while executing task 8
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at org.mcstats.multiverse.Metrics.postPlugin(Metrics.java:357) ~[?:?]
        at org.mcstats.multiverse.Metrics.access$400(Metrics.java:64) ~[?:?]
        at org.mcstats.multiverse.Metrics$1.run(Metrics.java:245) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_66]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
[19:24:24 INFO]: [Vault] Checking for Updates ...
[19:24:25 INFO]: [ShopChest] Checking for updates...
[19:24:25 INFO]: [ShopChest] No new update available.
[19:24:25 WARN]: [CraftBook] ºcWarning! You have no mechanics enabled, the plugin will appear to do nothing until a feature is enabled!
[19:24:25 INFO]: [Vault] No new version available
[19:24:53 INFO]: UUID of player The_SethLord is 89506164-af37-499c-b4d7-874f30ede64a
[19:24:53 INFO]: The_SethLord[/192.168.2.105:51303] logged in with entity id 342 at ([world]237.41617990329536, 70.0, 248.877935120646)
[19:25:07 INFO]: The_SethLord issued server command: /gamemode 1
[19:25:07 INFO]: [The_SethLord: Set own game mode to Creative Mode]
**[19:25:33 INFO]: The_SethLord issued server command: /mvp create Survival Survivalness**
**[19:25:33 INFO]: WEAPI
[19:25:33 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.4-b548
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_66]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getSelectionWorld()Lcom/sk89q/worldedit/LocalWorld;
        at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedRegion(PortalPlayerSession.java:169) ~[?:?]
        at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:56) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
        at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:317) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.11.2.jar:git-Spigot-4741400-a1d3777]
        ... 15 more
>**

**Comment by JamesTheAwesomeDude** [comment] 2017-02-09 02:48
I'm getting this, too (Multiverse-Core v2.5-b719 @ PaperSpigot git-Paper-1053)

````
[20:46:36 INFO]: codegeek98 issued server command: /mvp create hut e:creative_world:-103,62,-623
[20:46:36 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.4-b548
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PaperSpigot-latest.jar:git-Paper-1053]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[PaperSpigot-latest.jar:git-Paper-1053]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:675) ~[PaperSpigot-latest.jar:git-Paper-1053]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1384) ~[PaperSpigot-latest.jar:git-Paper-1053]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189) ~[PaperSpigot-latest.jar:git-Paper-1053]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[PaperSpigot-latest.jar:git-Paper-1053]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[PaperSpigot-latest.jar:git-Paper-1053]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[PaperSpigot-latest.jar:git-Paper-1053]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [PaperSpigot-latest.jar:git-Paper-1053]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:830) [PaperSpigot-latest.jar:git-Paper-1053]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [PaperSpigot-latest.jar:git-Paper-1053]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [PaperSpigot-latest.jar:git-Paper-1053]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [PaperSpigot-latest.jar:git-Paper-1053]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at com.onarandombox.MultiversePortals.MVPortal.addToUpperLists(MVPortal.java:157) ~[?:?]
	at com.onarandombox.MultiversePortals.MVPortal.init(MVPortal.java:92) ~[?:?]
	at com.onarandombox.MultiversePortals.MVPortal.<init>(MVPortal.java:61) ~[?:?]
	at com.onarandombox.MultiversePortals.MVPortal.<init>(MVPortal.java:219) ~[?:?]
	at com.onarandombox.MultiversePortals.utils.PortalManager.addPortal(PortalManager.java:126) ~[?:?]
	at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:62) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
	at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:317) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PaperSpigot-latest.jar:git-Paper-1053]
	... 15 more
````

**Comment by Jadiction** [comment] 2019-06-09 04:43
Duplicate of https://github.com/Multiverse/Multiverse-Portals/issues/484

**Closed by Jadiction** 2019-06-09 04:43 UTC
Labels: Duplicate
