### ISSUE TITLE
Allow non-cuboid selections

### ISSUE THREAD

**Issue by xOrlxndo** [Multiverse/Multiverse-Portals#472] opened 2018-05-08 00:09 UTC
Hello,
The plugin doesn't seem to work with selections other than a standard cuboid selection in worldedit. Please add support for non-cuboid selections when using worldedit when using /mvp create

**Comment by Jadiction** [comment] 2019-06-09 05:08
Duplicate of https://github.com/Multiverse/Multiverse-Portals/issues/446

**Closed by Jadiction** 2019-06-09 05:08 UTC
Labels: Duplicate
