### ISSUE TITLE
use portal with boat

### ISSUE THREAD

**Issue by RCEKH** [Multiverse/Multiverse-Portals#253] opened 2013-04-20 08:59 UTC
Hi,
have problem that user can use a portal with a boat.
the boat will destroyed or the player pass the portal without teleport.
But inside the config is written :    teleportnonplayers: true

Please help me, we want to create a Venezia-Town, xD.

**Comment by FernFerret** [comment] 2016-03-06 22:29
Closing as duplicate of https://github.com/Multiverse/Multiverse-Portals/issues/267

**Closed by FernFerret** 2016-03-06 22:29 UTC
