### ISSUE TITLE
Add feature to move 1 block out of portal on teleport

### ISSUE THREAD

**Issue by danielfr789** [Multiverse/Multiverse-Portals#243] opened 2013-03-17 00:18 UTC
When you go through portal a, instead of being teleported to the inside of portal b, you get teleported 1 block out.

Also as another suggestion add an option to what direction you face when you go through a portal.

**Comment by FernFerret** [comment] 2016-03-06 22:34
Closing as duplicate of https://github.com/Multiverse/Multiverse-Portals/issues/411

**Closed by FernFerret** 2016-03-06 22:34 UTC
Labels: Duplicate
