### ISSUE TITLE
Minecarts and Multiverse Portals in 1.6.2

### ISSUE THREAD

**Issue by Godson777** [Multiverse/Multiverse-Portals#283] opened 2013-08-31 15:53 UTC
Okay, so before I begin, I'm using version 2.4-AB.

So I have this minecart redstone machine that would need to use Multiverse's portals in order to warp to the town you would select in the machine. However, when riding a minecart through the portal, nothing happens. I went right through the portal without warping. I tried sending a boat through it, and I ended up getting pushed back, same applies for the minecart if I were moving slowly. Is there any way to fix this? Do I have to download a dev build or something?

**Comment by Jadiction** [comment] 2019-06-09 05:04
Duplicate of https://github.com/Multiverse/Multiverse-Portals/issues/267

**Closed by Jadiction** 2019-06-09 05:04 UTC
Labels: Duplicate
