### ISSUE TITLE
World doesn't load when going through portal in minecart 

### ISSUE THREAD

**Issue by ghost** [Multiverse/Multiverse-Portals#148] opened 2012-04-04 18:41 UTC
When going through a portal in a minecart, the world will not load, resulting in a void blue world. The player has to log out and back in for the world to load.

**Comment by FernFerret** [comment] 2016-03-09 05:57
I know this is a duplicate of another... just can't remember for now. Anywho, OP user deleted account, closing. Please reopen if someone else is interested.

**Closed by FernFerret** 2016-03-09 05:57 UTC
