### ISSUE TITLE
Won't Teleport Minecart

### ISSUE THREAD

**Issue by MrMord** [Multiverse/Multiverse-Portals#368] opened 2015-02-15 01:42 UTC
I'm running CraftBukkit version git-spigot-b8f6402-a646500 (MC: 1.8) (Implementing version 1.8-RO.1-SNAPSHOT); MV Portals version 2.5-b713.

I've used MVP before to teleport minecarts and had a glitch where it got stuck in a loop...but that's beside the point. This time, it won't even teleport the minecart--even with the setting "teleportvehicles: true". I've also tried "false" and gotten the same result. And yes, I've made sure the minecart has room to fully enter the portal.

Any ideas with this?

**Comment by mvaughn-echo** [comment] 2015-05-24 21:30
Reproducible with no other plugins installed in a flat-type normal world called 'world' on spigot-1.8.3.

Is anyone committing to this repository anymore? :(

**Comment by MrMord** [comment] 2015-05-29 02:57
Seems not. I think a lot of people gave up with the whole spigot/bukkit dispute with 1.8
It's hard to come by good quality plugins these days, and this was one of them. Hope they can bring it back :(

**Comment by FernFerret** [comment] 2016-03-06 20:57
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

**Closed by FernFerret** 2016-03-06 20:57 UTC
