### ISSUE TITLE
Blocks facing the wrong direction after portal use

### ISSUE THREAD

**Issue by Zyles** [Multiverse/Multiverse-Portals#299] opened 2014-01-27 03:02 UTC
After portal use like 2-3 times some blocks are facing the wrong direction such as:

- Iron Furance
- Industrial Information Panel
- Information Panel Extender

Basically they are facing so the backside is out.

Running MCPC+ FTB Ultimate 1.4.7

**Comment by FernFerret** [comment] 2016-03-06 22:02
This is probably not caused by Multiverse Portals, some of these other mods (non CB or Spigot) do weird things with blockdata.

Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).

**Closed by FernFerret** 2016-03-06 22:02 UTC
